name: Windows11_25H2_amd64

on:
  workflow_dispatch:
    inputs:
      release:
        description: '上传Release'
        required: true
        type: choice
        options:
          - 'false'
          - 'true'

env:
  Build_VERSION: '26200.7922'
  FILE_NAME: Windows11_25H2_amd64

jobs:
  Windows11_25H2_amd64:
    runs-on: windows-latest

    steps:

    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v6

    # 制作ISO
    - name: UUP dump WinISO
      shell: cmd
      run: |
        cd ${{env.FILE_NAME}}
        dir
        uup_download_windows.cmd

    # 移动并重命名镜像
    - name: Rename
      shell: cmd
      run: |
        dir  .\${{env.FILE_NAME}}
        move  .\${{env.FILE_NAME}}\${{env.Build_VERSION}}*.iso .\${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso
        dir

    # 上传镜像
    - uses: actions/upload-artifact@v6
      with:
        name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        path: ${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso

    # 打包
    - name: Package binaries
      if: ${{ github.event.inputs.release == 'true' }}
      run: |
        7z a -v1950M ${{env.FILE_NAME}}.${{env.Build_VERSION}}.7z ./${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso -mx=9

    # 发布镜像
    - name: Release
      if: ${{ github.event.inputs.release == 'true' }}
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        files: ${{env.FILE_NAME}}.${{env.Build_VERSION}}.7z*
